export const QUOTE_STATUSES = [
  "DRAFT",
  "QUOTED",
  "CONSUMED",
  "EXPIRED",
  "CANCELED",
] as const;

export const DELIVERY_STATUSES = [
  "SEARCHING_DRIVER",
  "DRIVER_ASSIGNED",
  "TO_PICKUP",
  "ARRIVED_PICKUP",
  "PICKED_UP",
  "TO_DROPOFF",
  "ARRIVED_DROPOFF",
  "DELIVERED",
  "RETURN_REQUIRED",
  "RETURNING",
  "RETURNED",
  "CANCELED",
  "FAILED",
] as const;

export const TERMINAL_DELIVERY_STATUSES = [
  "DELIVERED",
  "RETURNED",
  "CANCELED",
  "FAILED",
] as const;

export const OTP_ALLOWED_STATES = [
  "PICKED_UP",
  "TO_DROPOFF",
  "ARRIVED_DROPOFF",
] as const;

export const INCIDENT_STATUSES = [
  "OPEN",
  "UNDER_INVESTIGATION",
  "RESOLVED_CONTINUE",
  "RESOLVED_RETURN",
  "RESOLVED_HANDOFF",
  "CLOSED",
] as const;

export const INCIDENT_TYPES = [
  "VEHICLE_BREAKDOWN",
  "ACCIDENT",
  "GPS_LOST",
  "NETWORK_LOST",
  "PACKAGE_DAMAGED",
  "BUSINESS_CLOSED",
  "PACKAGE_NOT_READY",
  "CUSTOMER_UNREACHABLE",
  "RECIPIENT_REFUSED",
  "ADDRESS_PROBLEM",
  "PAYMENT_PROBLEM",
  "CASH_MISMATCH",
  "SAFETY_ISSUE",
  "OTHER",
] as const;

export const OFFER_STATUSES = [
  "OPEN",
  "ACCEPTED",
  "REJECTED",
  "EXPIRED",
  "CANCELED",
] as const;

export const DRIVER_VERIFICATION_STATUSES = [
  "PENDING",
  "UNDER_REVIEW",
  "VERIFIED",
  "REJECTED",
  "EXPIRED",
] as const;

export const DRIVER_ACCOUNT_STATUSES = [
  "REGISTERED",
  "ACTIVE",
  "SUSPENDED",
  "BLOCKED",
  "CLOSED",
] as const;

export const DRIVER_OPERATIONAL_STATES = [
  "OFFLINE",
  "AVAILABLE",
  "OFFERED",
  "BUSY",
  "PAUSED",
] as const;

export const BUSINESS_VERIFICATION_STATUSES = [
  "NOT_REQUIRED",
  "PENDING",
  "UNDER_REVIEW",
  "VERIFIED",
  "REJECTED",
] as const;

export const BUSINESS_ACCOUNT_STATUSES = [
  "ACTIVE",
  "SUSPENDED",
  "BLOCKED",
  "CLOSED",
] as const;

export const BUSINESS_MEMBER_ROLES = [
  "business_owner",
  "business_manager",
  "business_employee",
] as const;

export const PLATFORM_ROLES = [
  "super_admin",
  "admin",
  "operator",
  "verification_agent",
  "none",
] as const;

export const PRICING_ADJUSTMENT_TYPES = [
  "WAITING_FEE",
  "RETURN_FEE",
  "CANCEL_FEE",
  "DISCOUNT",
  "SUBSIDY",
  "MANUAL_ADJUSTMENT",
] as const;

export const HANDOFF_STATUSES = [
  "INITIATED",
  "CONFIRMED_FROM",
  "CONFIRMED_TO",
  "COMPLETED",
  "ABORTED",
] as const;

export const PAYOUT_STATUSES = [
  "REQUESTED",
  "UNDER_REVIEW",
  "APPROVED",
  "PROCESSING",
  "PAID",
  "REJECTED",
  "FAILED",
] as const;

export const PAYMENT_STATUSES = [
  "PENDING",
  "AUTHORIZED",
  "CAPTURED",
  "FAILED",
  "REFUNDED",
] as const;

export const CASH_SETTLEMENT_STATUSES = [
  "PENDING",
  "UNDER_REVIEW",
  "SETTLED",
  "DISCREPANCY",
  "REJECTED",
] as const;

export const NOTIFICATION_STATUSES = [
  "QUEUED",
  "SENDING",
  "DELIVERED",
  "FAILED_RETRYABLE",
  "FAILED_PERMANENT",
] as const;

export const BUSINESS_MEMBER_STATUSES = [
  "ACTIVE",
  "INVITED",
  "SUSPENDED",
] as const;

export const DOCUMENT_VERIFICATION_STATUSES = [
  "PENDING",
  "UNDER_REVIEW",
  "VERIFIED",
  "REJECTED",
  "EXPIRED",
] as const;

export const PAYOUT_METHOD_VERIFICATION_STATUSES = [
  "PENDING",
  "VERIFIED",
  "REJECTED",
  "DISABLED",
] as const;

export const TRACKING_FRESHNESS_LEVELS = [
  "FRESH",
  "DELAYED",
  "STALE",
  "UNAVAILABLE",
] as const;

export const PROOF_TYPES = [
  "PICKUP_CUSTODY",
  "DELIVERY_PHOTO",
  "DELIVERY_SIGNATURE",
  "RETURN_PROOF",
  "HANDOFF_PROOF",
] as const;

export const EVENT_TYPES = [
  "DELIVERY_CREATED",
  "SEARCH_STARTED",
  "OFFER_CREATED",
  "OFFER_ACCEPTED",
  "DRIVER_ASSIGNED",
  "TO_PICKUP_STARTED",
  "ARRIVED_PICKUP",
  "CUSTODY_TRANSFERRED",
  "TO_DROPOFF_STARTED",
  "ARRIVED_DROPOFF",
  "OTP_VERIFIED",
  "DELIVERY_COMPLETED",
  "RETURN_REQUIRED",
  "RETURN_STARTED",
  "RETURN_COMPLETED",
  "HANDOFF_STARTED",
  "HANDOFF_CONFIRMED_FROM",
  "HANDOFF_COMPLETED",
  "HANDOFF_ABORTED",
  "INCIDENT_OPENED",
  "INCIDENT_RESOLVED",
  "INCIDENT_RESOLVED_ADMIN",
  "DRIVER_UNASSIGNED",
  "DELIVERY_CANCELED",
  "DELIVERY_FORCE_CANCELED",
  "DELIVERY_FAILED",
  "QUOTE_CALCULATED",
  "QUOTE_CONSUMED",
  "QUOTE_EXPIRED",
  "QUOTE_CANCELED",
  "OFFER_EXPIRED",
  "OFFER_REJECTED",
  "OFFER_CANCELED",
  "SEARCH_EXPANDED",
  "MAPS_FALLBACK_USED",
  "WAITING_STARTED",
  "OTP_ATTEMPT_FAILED",
  "OTP_LOCKED",
  "PAYMENT_INITIATED",
  "PAYMENT_AUTHORIZED",
  "PAYMENT_CAPTURED",
  "PAYMENT_FAILED",
  "PAYMENT_REFUNDED",
  "DRIVER_SUSPENDED",
  "DRIVER_REACTIVATED",
  "BUSINESS_SUSPENDED",
  "BUSINESS_REACTIVATED",
  "RETURN_AUTHORIZED",
  "CUSTODY_RETURNED",
  "DRIVER_REGISTERED",
  "DRIVER_VERIFIED",
  "DRIVER_REJECTED",
  "DOCUMENT_SUBMITTED",
  "VEHICLE_REGISTERED",
  "AVAILABILITY_CHANGED",
  "PAYOUT_METHOD_ADDED",
  "PAYOUT_METHOD_DISABLED",
  "PAYOUT_REQUESTED",
  "PAYOUT_APPROVED",
  "PAYOUT_REJECTED",
  "CASH_SETTLED",
  "BUSINESS_CREATED",
  "LOCATION_ADDED",
  "MEMBER_ADDED",
  "MEMBER_REMOVED",
  "SUPPORT_TICKET_CREATED",
  "PRICING_VERSION_ACTIVATED",
] as const;
